export const UPLOAD_DATA = 'UPLOAD_DATA';
export const CLEAR_SECTION = 'CLEAR_SECTION';
export const SORT_SECTION = 'SORT_SECTION';
export const FILTER_SECTION = 'FILTER_SECTION';
export const SEND_CARD = 'SEND_CARD';
export const DRAW_CARD = 'DRAW_CARD';
export const SELECT_CARD = 'SELECT_CARD';
export const CLOSE_TESTHAND_MODAL = 'CLOSE_TESTHAND_MODAL';
export const OPEN_TESTHAND_MODAL = 'OPEN_TESTHAND_MODAL';
export const OPEN_CLEAR_WARNING_MODAL = 'OPEN_CLEAR_WARNING_MODAL';
export const CLOSE_CLEAR_WARNING_MODAL = 'CLOSE_CLEAR_WARNING_MODAL';
export const OPEN_ENLARGED_CARD_MODAL = 'OPEN_ENLARGED_CARD_MODAL';
export const CLOSE_ENLARGED_CARD_MODAL = 'CLOSE_ENLARGED_CARD_MODAL';
export const HIDE_UPLOAD_FAIL_ALERT = 'HIDE_UPLOAD_FAIL_ALERT';

